### ISSUE TITLE
Permanently excluding paths/files

### ISSUE THREAD

**Issue by Zirro** [sveinbjornt/Sloth#12]
Certain files are very common among open applications. Some examples I see includes `ci_stdlib.metallib`, `ci_filters.metallib`, `Cache.db*`. They're rarely of interest and more of a distraction.

It could be quite helpful if we had the ability to save a list of patterns with paths/filenames that we'd like to exclude permanently from the listing.

**Comment by sveinbjornt** [comment]
Good idea. Will implement in Sloth 3.0.

**Comment by sveinbjornt** [comment]
Will implement in 3.1.
