### ISSUE TITLE
Refreshing the list at an interval

### ISSUE THREAD

**Issue by Zirro** [sveinbjornt/Sloth#13]
In some situations it's useful to observe rapid changes to which files are open. It seems like the list can currently only be refreshed manually with the Refresh button.

It would be handy if there was an option for automatically refreshing the list every X seconds (while keeping the same entries in the list expanded as before) to help observe changes to it.

**Comment by sveinbjornt** [comment]
This is a good idea, will implement in Sloth 3.0.

**Comment by sveinbjornt** [comment]
Will implement in 3.1.
