### ISSUE TITLE
sveinbjorn.org appears to be down.

### ISSUE THREAD

**Issue by iron0012** [sveinbjornt/Sloth#17]
sveinbjorn.org is currently unresponsive, which makes both the download link (https://sveinbjorn.org/files/software/sloth.zip) and the homebrew recipe inoperable.

**Comment by sveinbjornt** [comment]
Yeah, the server is down. Working on getting things fixed.

**Comment by sveinbjornt** [comment]
Meanwhile, you can download the latest release here on GitHub:

https://github.com/sveinbjornt/Sloth/releases
