### ISSUE TITLE
Notarization

### ISSUE THREAD

**Issue by x13a** [sveinbjornt/Sloth#19]
Hello.

It seems that version 3.1 is not notarized. Maybe someone with Apple Developer ID can upload it to Apple? As i know, anyone with valid DevID can do this.

Related: [18](https://github.com/sveinbjornt/Sloth/issues/18)

**Comment by sveinbjornt** [comment]
I'm not interested in notarizing the apps I'm developing. It's annoying enough to have to jump through a million hoops to code-sign them whilst paying [!] Apple for the "privilege".
