### ISSUE TITLE
brew install --cask sloth fails

### ISSUE THREAD

**Issue by smnbbrv** [sveinbjornt/Sloth#21]
Hi, the tool cannot be installed on mac

> Error: Download failed on Cask 'sloth' with message: Download failed: https://sveinbjorn.org/files/software/sloth/sloth-3.1.zip

**Comment by sveinbjornt** [comment]
My server is down at the moment due to hardware failure. Hopefully I'll be be able to get it up and running again over the weekend.

**Comment by smnbbrv** [comment]
super, thank you for the so quick response!

May I ask why can't it be installed from github releases? (this would significantly reduce the amount of issues like this one)

**Comment by sveinbjornt** [comment]
https://github.com/sveinbjornt/Sloth/releases/tag/3.1

In theory there's no reason why the homebrew formula couldn't use the link to the prebuilt app on GitHub. But I do not maintain the formula...
