### ISSUE TITLE
A way to use Touch ID instead of having to enter password every time

### ISSUE THREAD

**Issue by melyux** [sveinbjornt/Sloth#22]
Sloth requires sudo privileges to see the list of open files, but won't take Touch ID. You have to type your password every time, and it expires after a few minutes so you have to do it again.

If the user [enables Touch ID for sudo](https://azimi.io/how-to-enable-touch-id-for-sudo-on-macbook-pro-46272ac3e2df), he should be able to use Touch ID. Even for apps that don't specifically go out of their way to support Touch ID natively, them using sudo internally is enough to bring up the Touch ID prompt successfully (like Balena Etcher).

Can Sloth also do this instead of exclusively asking for the password?

**Comment by sveinbjornt** [comment]
This is not going to happen.

**Comment by sveinbjornt** [comment]
If typing the password really bothers you, just run Sloth via sudo:

````
sudo ./Applications/Sloth.app/Contents/MacOS/Sloth
````
