### ISSUE TITLE
keep "dead" processes around

### ISSUE THREAD

**Issue by maxandersen** [sveinbjornt/Sloth#27]
Just discovered Sloth and really like it.

Unfortunately I'm running into issue that some of my apps don't stay around for long and a manual or auto refresh make me loose them.

Would be awesome if there was a way to keep "dead" processes around until explicitly pruned/cleared.

**Comment by sveinbjornt** [comment]
Not really, I'm afraid. Sloth is just a front-end for lsof and limited by its capabilities.

**Comment by maxandersen** [comment]
@sveinbjornt I get its a front-end but couldn't it keep last reported/collected data around instead of only show current data?
