### ISSUE TITLE
ЙI process

### ISSUE THREAD

**Issue by yoav-lavi** [sveinbjornt/Sloth#3]
Hi, I'm getting a process called "ЙI" with a few open handles. When looking at the handles themselves, they seem to be used by `lsof`, not "ЙI". Killing the process just causes it to reopen. It is not listed in `ps aux` by the specified ID. Is this a bug? or a rogue process on my machine? I'm assuming this is some issue with Sloth detecting itself, but I'd like to hear your input.
Using version 2.6.
I've also seen the same process named "z" after reopening Sloth, and upon reopening again it was gone (with `lsof` seemingly using the same handles).

**Comment by sveinbjornt** [comment]
Lsof (and, by extension, Sloth) should have no problem listing itself. Do you also get these weird processes when running `/usr/bin/lsof` from the command line? If it's behaviour in lsof itself, there's not much I can do about it.

**Comment by 0xced** [comment]
Maybe #7 (commit 063d488e161ab6e4297540c6811f8fda11962c61) will fix this issue.
