### ISSUE TITLE
Also show/determine windows

### ISSUE THREAD

**Issue by doekman** [sveinbjornt/Sloth#30]
This is a feature request. Maybe it doesn't fit, but I thought it would, so let me know.

I had a hanging window on my mac (some 3rd party payment authorisation when renewing my Apple ID) I couldn't get rid of. When I clicked on the window, the app-name in the menu didn't change. So I couldn't find out what process the window belonged to, so I couldn't kill it.

Wouldn't it be nice if there also was a checkbox "windows". And maybe also an option to select a window to determine the process (a bit like "Select element" in the web browser's developer tools).

In the end I used [this python3 script](https://apple.stackexchange.com/a/449045) from stackexchange to determine the window, but it could be easier...

**Comment by sveinbjornt** [comment]
This doesn't really fit within the intended functionality of Sloth but thanks for bringing up the idea.
