### ISSUE TITLE
App is not notarized

### ISSUE THREAD

**Issue by doekman** [sveinbjornt/Sloth#31]
(screenshots from the Dutch localization of MacOS, but I'm sure you recognize the screens)

When I installed the app via home-brew, I couldn't start it (popup: no-open-1.png).

<img width="385" alt="no-open-1" src="https://github.com/sveinbjornt/Sloth/assets/1086388/f3622e24-08a1-4fdb-a46d-6d94c890a4db">

Via "System Settings > Privacy and security > Open Anyways" (screenshot: open-anyways.png)...

<img width="499" alt="open-anyways" src="https://github.com/sveinbjornt/Sloth/assets/1086388/5aa4d8e4-14c7-44fd-adb0-36a2a19deae6">

...I was able to start the app (getting another popup: confirm-open-1.png) by pressing "Open" on the popup.

<img width="385" alt="confirm-open-1" src="https://github.com/sveinbjornt/Sloth/assets/1086388/0d0feffe-144d-4b10-a0e0-a57f8581da3a">

According to Apparency.app your app is signed, but not notarized (apparancy-sloth.png).

<img width="341" alt="apparancy-sloth" src="https://github.com/sveinbjornt/Sloth/assets/1086388/dbc72f4b-64d9-4b50-b47d-09019c8520b9">

My guess (I'm not sure, not an expert) is notarizing solves the problem.

**Comment by Aces-and-Jacks** [comment]
Pretty late but if you right click the app and click open it'll offer the option to open up anyway. They probably don't want to notarize the app since it'll cost yearly and don't want to spend on something like that. A lot of app developers do that

**Comment by doekman** [comment]
No worries. As long as you are aware of it.
