### ISSUE TITLE
Mention about brew cask on README file

### ISSUE THREAD

**Issue by FrankKair** [sveinbjornt/Sloth#6]
Hey, Sveinbjörn.
First of all, this is a pretty nice app, congrats! 😊

Have you thought of using `brew cask` to distribute de app, so that people can install it from the command line? That would be neat.

What do you think?

**Comment by Extrawurst** [comment]
someone took care of that already: http://macappstore.org/sloth/
it is unfortunately not mentioned here. but u can simply do `brew cask install sloth`

**Comment by FrankKair** [comment]
Oh, thank you very much @Extrawurst!
This issue should be renamed to "Add brew cask to README file" then 😅

**Comment by sveinbjornt** [comment]
Fixed in master. README now also notes that Sloth can be installed via Homebrew.
