### ISSUE TITLE
.DS_Store?

### ISSUE THREAD

**Issue by Henrietta1989** [sveinbjornt/Sloth#8]
Why Sloth lists lots of /Volumes/path_here/.DS_Store files which are open by mdworker and mdworker_shared?

I use Sloth to see if Spotlight have already finished reindexing.

**Comment by sveinbjornt** [comment]
I'm not sure I understand your question. Are you asking why Sloth is listing these files? It lists them because they are open and being used by the processes in question. Or are you asking why those processes have these files open? The answer to that question lies with Apple's engineers.
